name: CI - Train & Deploy Model

on:
  push:
    paths:
      - "MLProject/**"
      - ".github/workflows/**"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MLflow Project
      working-directory: MLProject
      run: |
        mlflow run . --env-manager=local

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/diabetes-ml-ci:latest MLProject
        docker push ${{ secrets.DOCKER_USERNAME }}/diabetes-ml-ci:latest
